### ISSUE TITLE
About train code

### ISSUE THREAD

**Issue by chenqihuang** [StrangerZhang/SiamFC-PyTorch#1]
Thanks to the pytorch version of siamesefc. Can you provide the completed code to generate the OTB results?

**Comment by StrangerZhang** [comment]
use this repo(https://github.com/bilylee/tracker_benchmark.git) to generate OTB results

**Comment by vincennnnt** [comment]
@QiHuangChen Sorry to interrupt you，did you succeed to evaluate the OTB results？And I don‘t exactly know how to use the repo（https://github.com/bilylee/tracker_benchmark.git.

**Comment by jensenzhoujh** [comment]
you could put run_SiamFC.py and folder siamfc in this repo to a newly established folder as 'SiamFC' in 'trackers' of  this repo (https://github.com/bilylee/tracker_benchmark.git). Note that few more modifications are required. @vincennnnt
