### ISSUE TITLE
There is no fire  when i  execute  python bin/demo_siamfc？

### ISSUE THREAD

**Issue by bigmoking** [StrangerZhang/SiamFC-PyTorch#14]
File "bin/demo_siamfc.py", line 11, in <module>
    from fire import Fire   ImportError: No module named fire

**Comment by StrangerZhang** [comment]
pip install fire
should solve your problem

**Comment by bigmoking** [comment]
I have a error that "AttributeError: 'Variable' object has no attribute 'shape' "
What's your version of the pytorch?

**Comment by StrangerZhang** [comment]
pytorch 0.4.1 & python 3.6
