### ISSUE TITLE
How to solve the LMDB error in SiamFC training

### ISSUE THREAD

**Issue by 284513016** [StrangerZhang/SiamFC-PyTorch#18]
I'm following your instructions to run to   python bin/train_siamfc.py --gpu-id [gpu_id] --data-dir path/to/data/ILSVRC2015_VID_CURATION. But the system reported an error.
lmdb error ;path/to/data/ILSVRC2015_VID_CURATION
How to solve this problem? 
Thank you very much

**Comment by 284513016** [comment]
@StrangerZhang

**Comment by universefall** [comment]
I have some problem. How did you solve it? Thank you
