### ISSUE TITLE
The training speed is low on 1080Ti.

### ISSUE THREAD

**Issue by ZSQflower** [StrangerZhang/SiamFC-PyTorch#3]
Training phase costs about 12 hrs on a single 1080ti.

**Comment by ZSQflower** [comment]
Why did u say 'training should take about 1.5~2hrs on a Titan Xp GPU with 30 epochs'? 1080Ti should have  comparable training speed? But I the traning phase for 30 epochs costs about 12 hours... Can u help me. @StrangerZhang

**Comment by StrangerZhang** [comment]
Did you use the latest code with git pull.

Maybe data loading is slow, check your train_num_workers in config.py

**Comment by ZSQflower** [comment]
Thanks, train_num_workers is set to 8. I changed some API to use the code under pytorch 0.3.1 env. Maybe this could have an impact on the traning speed?

**Comment by StrangerZhang** [comment]
Maybe, my pytorch version is 0.4.1, could you update your pytorch version, and train it again, if the speed is not like I say, let my know

**Comment by ZSQflower** [comment]
ok, ill have a try

**Comment by ZSQflower** [comment]
The issue arises from the dataloader. The forward time of the network is fine, but the dataloader take much more time occasionally. I ll change the pytorch version. Any other potential issues about the dataloader?

**Comment by StrangerZhang** [comment]
Did you use lmdb to load data? I changed my code recently in order to speed up the data loading speed

**Comment by ZSQflower** [comment]
yes lmdb is used.
