### ISSUE TITLE
question about computing displacement in interpolation response

### ISSUE THREAD

**Issue by happyjin** [StrangerZhang/SiamFC-PyTorch#5]
Hi StrangerZhang:
Thanks for your wonderful code. I have a question about computing displacement in interpolation response. Can you please tell me the intuition of this computation? Why does the code need to minus half of interp_response_sz? Thanks in advance!

**Comment by ZSQflower** [comment]
I think the output heatmap describes the translation of the target from the center position of the search patch image. Thus minusing half the size to calculate the translation (displacement).

**Comment by happyjin** [comment]
@ZSQflower  Thanks for your swift reply. It makes sense. Can you please explain a bit more about displacement in instance frame namely `disp_instance_frame = disp_instance_input * (self.s_x * scale) / config.instance_size`? I am curious about why the disp_instance_input needs to time s_x at first then divided by instance_size.

**Comment by ZSQflower** [comment]
@happyjin  '/ config.instance_size'  is aimed to normalize the coordinate, '(self.s_x * scale)' is aimed to rescale the coordinate to original search patch.  It could be easier to understand 'first divided by instance_size then time s_x '.

**Comment by happyjin** [comment]
Hi @ZSQflower 
Do you know how to evaluate the tracker in the OTB toolkit? I saw there is 'run_SiamFC.py' in 'bin' folder which might used for OTB evaluation. However, OTB benchmark toolkit from official can only evaluate Matlab tracker. Can you please tell me how to evaluate this Python tracker in the OTB benchmark toolkit? Thanks in advance!

**Comment by StrangerZhang** [comment]
@happyjin 
you can use this [repo](https://github.com/StrangerZhang/pysot-toolkit) to test your tracker
